name: AWVS14_Update
  
on:
  repository_dispatch:
    types: [Awvs_Update_Action]
  workflow_dispatch:

jobs:
  AWVS14_Update:
    name: AWVS14_Update
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Check The Update
        run: |  
          wget -O tmpREADME.md "$(curl -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.TOKEN_GITHUB }} -s 'https://api.github.com/repos/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_GITHUB }}/contents/README.md' | grep download_url | cut -d '"' -f 4)"
          if [ "$(md5sum README.md | awk '{print 1}')" != "$(md5sum tmpREADME.md | awk '{print 1}')" ]; then
          	echo ::set-env name=md5Status::true
            rm README.md
            mv tmpREADME.md README.md
          fi
      - 
        name: Upgrade README & Upgrade Web Page
        if:  env.md5Status == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes by Awvs_Update_Action" -a
          curl -s ${{ secrets.WebHock }}
      - 
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: ${{ github.ref }}
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
